### ISSUE TITLE
Install of GEMINI

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#20] opened 2015-11-04 01:40 UTC
I attempted to install this software- which is needed for speedseq- and ran into problem.  Ultimately this is a tool that many people in the lab will want to use as a stand alone tool and it would be good if we could install and make a module for this software- as it has a lot of dependencies.  

http://gemini.readthedocs.org/en/latest/content/installation.html#software-dependencies

Note that the gemini installer script did not ultimately end up working when I tried to use it.

**Comment by tatarsky** [comment] 2015-11-04 01:56
Yeah, thats a monster. Running it but we'll see how it goes. More tomorrow.

**Comment by tatarsky** [comment] 2015-11-04 02:15
Placing this here for my notes. Not done yet and will make a module if tests pass.

```

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 38a0ff8... update history
Finished: gemini, tools and data installed
 Tools installed in:
  /frazer01/software/gemini-20151103
 Data installed in:
  /frazer01/software/gemini-20151103/share
 Run tests with:
  cd /frazer01/software/gemini-20151103/share/gemini && bash master-test.sh
 NOTE: be sure to add /frazer01/software/gemini-20151103/bin to your PATH.
 NOTE: Install data files for GERP_bp & CADD_scores (not installed by default).
```

**Comment by tatarsky** [comment] 2015-11-04 14:45
More downloads now in progress.

**Comment by tatarsky** [comment] 2015-11-04 14:56
Tests are passing but due to using sqlite we need to enable POSIX file locking on our Lustre mount. I have done this on the second head node to confirm.

However, could you please do some tests on hn1 (which I have not remounted with POSIX locks yet) to see if those sqlite needs are just part of the test routines?

I have the following modules ready for testing:

```
module add root speedseq gemini
```

**Comment by djakubosky** [comment] 2015-11-04 16:10
Great, will test and report back

On Wednesday, November 4, 2015, tatarsky notifications@github.com wrote:

> Tests are passing but due to using sqlite we need to enable POSIX file
> locking on our Lustre mount. I have done this on the second head node to
> confirm.
> 
> However, could you please do some tests on hn1 (which I have not remounted
> with POSIX locks yet) to see if those sqlite needs are just part of the
> test routines?
> 
> I have the following modules ready for testing:
> 
> module add root speedseq gemini
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/20#issuecomment-153752659.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by djakubosky** [comment] 2015-11-04 20:47
We need pysam in python27

**Comment by tatarsky** [comment] 2015-11-04 20:55
Hmm. I thought I loaded that. Ah, the item I loaded does not work the way I thought...one moment.

**Comment by djakubosky** [comment] 2015-11-04 20:57
I think the problem is I need to revert to the systems py27- what is the path to our system anaconda install? can I make a module to switch python environments out of my personal anaconda tree?

Sorry I thought this would happen when loading speedseq module

also, even when we switch it I think this will be an issue that we might have to mod a speedseq file to fix, found this thread with the same issue

https://github.com/hall-lab/speedseq/issues/52

**Comment by tatarsky** [comment] 2015-11-04 21:03
There isn't a system anaconda install. Just a load of a standard python-2.7 RPM from a repo that builds a good one. 

From what I saw the GEMINI package loads its own python and names it:

`gemini_python`

How are you trying to use items? Might be helpful to cut/paste some output. I don't know these packages well enough to advise you yet. I'm reading that Git. 

You wouldn't need a module to not use your own Anaconda. You would want to remove it from your PATH.

**Comment by cdeboever3** [comment] 2015-11-04 21:09
Not sure what your pysam problem is, but I know there are some big
differences between some pysam versions, so beware if they specify a pysam
version and you have a different one.

**Comment by cdeboever3** [comment] 2015-11-04 21:28
I don't mind if it's built against the system python, but ideally I'd like
to be able to call gemini from within an anaconda environment. I don't know
what that would do. I'll test it at some point.

**Comment by tatarsky** [comment] 2015-11-04 22:11
Yep. I'm getting the gist of how this is all wrapped....its a bit baroque.

**Comment by tatarsky** [comment] 2015-11-04 22:12
Gemini BTW carries around its OWN anaconda.

**Comment by tatarsky** [comment] 2015-11-04 22:12
Some of the above comments apply only to speedseq. I will likely delete them.

**Comment by tatarsky** [comment] 2015-11-12 12:52
I believe Gemini is installed as planned. I would like to close unless folks feel otherwise just for my "list management" purposes. If not yet confirmed or tested thats fine and I'll leave it open.

**Comment by cdeboever3** [comment] 2015-11-12 16:31
We haven't tested yet. I'm waiting for @HurleyLi's variant calling to
finish to test. I'm fine to close it and reopen if there is a problem. Up
to you.

**Comment by tatarsky** [comment] 2015-11-12 16:33
Nope, thats good enough for me to keep it open.

**Comment by cdeboever3** [comment] 2015-12-02 22:52
There is a new version of gemini that I'd like to update to before we (hopefully) begin extensively using gemini in the coming week. [See here for info.](https://groups.google.com/forum/#!topic/gemini-variation/lrUTurXWESE) In theory, a command line `gemini update -devel` should get us to the latest version ([see here](https://gemini.readthedocs.org/en/latest/#latest-news)). @tatarsky, do you want to try to update since you built this monster?

**Comment by tatarsky** [comment] 2015-12-03 02:14
Sure. I'll type that and see what happens.

**Comment by tatarsky** [comment] 2015-12-03 02:17
So it didn't seem to know what `-devel` meant. So I tried `gemini update`. Now waiting to see what comes out the other side.

**Comment by tatarsky** [comment] 2015-12-03 02:20
Ah, '--devel' now works.

**Comment by tatarsky** [comment] 2015-12-03 02:21
So I guess the main question now is "so does it still work?"

```
 gemini -v   
gemini 0.18.0
```

Over to you. I'm probably done tonight but will chek in morning.

**Comment by cdeboever3** [comment] 2015-12-03 02:44
Thanks. I plan on testing this week or next week. If it works fine, I'll
close the issue.

**Comment by tatarsky** [comment] 2015-12-03 13:22
OK. If it helps any I ran their "test process" after the update and I believe all tests said `ok`.

**Comment by tatarsky** [comment] 2016-01-05 15:10
I am doing some issue cleaning. I believe this is just waiting on time to check it works.

**Comment by cdeboever3** [comment] 2016-01-05 16:45
@hirokomatsui has been using this tool without issue so we can close for now. We'll open back up if something goes wrong.

**Closed as completed by cdeboever3** 2016-01-05 16:45 UTC
