### ISSUE TITLE
installing rgl package in R

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#98] opened 2016-01-14 00:08 UTC
I am trying to install rgl package in R but I get an error because X11 is not found:

configure: error: X11 not found but required, configure aborted.
ERROR: configuration failed for package 'rgl'

How can I solve this?

Thanks!

**Comment by s041629** [comment] 2016-01-14 00:28
I tried with both:
install.packages("rgl", repos = c("http://cran.us.r-project.org", getOption('repos')), dependencies = TRUE)

and:
install.packages("/frazer01/home/matteo/software/rgl_0.95.1441.tar.gz", repos = NULL, type="source")

**Comment by tatarsky** [comment] 2016-01-14 00:50
I'll take a look tomorrow if I get some time during my JHU project.
I assume this is a headnode and this is a build of R somewhere in your path.

**Comment by s041629** [comment] 2016-01-14 00:52
Correct: headnode (I will use this on a jupyter notebook) and R is in:
/frazer01/home/matteo/software/R-3.2.2/bin/R

**Comment by s041629** [comment] 2016-01-14 18:01
Hi Paul, I managed to make it work on my PC, so this is not urgent.

**Comment by tatarsky** [comment] 2016-01-14 19:42
OK. I am still doing upgrades. I was able to install this module in my account after adding some GL headers. I believe your error above is again due to a piece of software wanting to have `$DISPLAY` defined and you are not coming from a machine with X11. You might try similar fake DISPLAY exports similar to the root item reported awhile back.

**Comment by tatarsky** [comment] 2016-01-18 17:04
I have confirmed that the `rgl` R package requires a working and connectable X11 DISPLAY be set or the build fails. This is stunningly bad practice. But I have worked around it for you and added it for you. 

You need to investigate having an X11 server on the desktop you login from to reduce this class of issue if you want to use software that requires a forwarded X11 DISPLAY to build. 

Please test that RGL works (assuming you can without an X11 display) and close this at your leisure.

**Comment by s041629** [comment] 2016-01-18 17:52
I am running some jobs and it seems to be working. 

Thanks!

**Comment by tatarsky** [comment] 2016-01-18 17:53
Cool.

**Closed as completed by tatarsky** 2016-01-18 17:53 UTC
