### ISSUE TITLE
R-3.4.2

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#218] opened 2017-10-19 20:49 UTC
We are trying to install R-3.4.2 on flh2 and having an error during configure:
configure: error: libcurl >= 7.22.0 library and headers are required with support for https

Although I see libcurl and devel version 7.29.0 are installed. Can you check.

**Comment by tatarsky** [comment] 2017-10-19 20:52
Where is your source tree so I can look at the config.log?

**Comment by tatarsky** [comment] 2017-10-19 20:58
As usually that error is caused by something else....I've seen it before in several distros.

**Comment by s041629** [comment] 2017-10-19 21:01
/home/matteo/software/R-3.4.2

I tried also with the older version (R-3.4.1) in the same software folder, but I get the same error

**Comment by tatarsky** [comment] 2017-10-19 21:03
Grabbing tar ball and will look later today.

**Comment by tatarsky** [comment] 2017-10-19 21:05
I had no issues with configure. Do you perhaps have a module loaded that I do not @s041629 ?

Please provide the output of "module load" as your account or I can su to you. 

In particular I've seen issues when older gcc is used....

**Comment by s041629** [comment] 2017-10-19 21:10
I don't have any module loaded. I have "export PATH=/frazer01/home/matteo/software/R-3.2.2/bin:$PATH
" in my .bashrc. Does it influence the installation?

**Comment by tatarsky** [comment] 2017-10-19 21:13
I'm taking a look as you. I have reproduced the error as you and am seeing if I can spot what causes it for you. 

It might actually be you appear to have an anaconda curl-config which is then taken precedence from the system curl-config and may be missing something causing the config to exit.
```
checking for curl-config... /frazer01/home/matteo/anaconda2/bin/curl-config
checking libcurl version ... 7.49.0
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
checking if libcurl is version 7 and >= 7.22.0... no
configure: error: libcurl >= 7.22.0 library and headers are required with support for https
```

Can you perhaps place the system paths first and see if you get further?

**Comment by s041629** [comment] 2017-10-19 21:17
I commented everything in my .bashrc and now I can install. I will wait for the installation to be over before closing this thread

**Comment by tatarsky** [comment] 2017-10-19 21:18
It _might_ be because your personal curl is too _new_. I hit that somewhere and I'd have to check my notes what I did about it.

**Comment by tatarsky** [comment] 2017-10-19 21:28
Happy also BTW to make a global module for this version. I had built I think a R/3.4.0 module but its not the default. We should review as part of this process the module versions v.s. system versions and adjust defaults appropriately.

**Comment by s041629** [comment] 2017-10-19 21:31
Installation is over and R works fine. I have always had my private R version because I always install tons of packages

**Comment by tatarsky** [comment] 2017-10-19 21:32
Completely understand. Enjoy your R!

**Comment by tatarsky** [comment] 2017-10-23 18:15
Believed resolved. Re-open if not.

**Closed as completed by tatarsky** 2017-10-23 18:15 UTC
