### ISSUE TITLE
Django Server Not Receiving Get Requests 

### ISSUE THREAD

**Issue by joreynajr** [frazer-lab/cluster#96] opened 2016-01-09 00:54 UTC
We have been having issues hosting Django websites on flh1. Some people can access Django websites and other can't. 
- This isn't an operating system specific problem because the issue seems not to discriminate between OS's; some people have macs and it works/or fails, same for windows. 
- It doesn't seem to be a browser specific issue because I have tried out Firefox, Internet Explorer, and Google Chrome. Even turning off all security measures like FireWall, etc don't do a thing. 
- Sometimes it seems to work for someone but the next moment it may stop working. 

From monitoring the Django web server I can see successful hits resulting in GET requests to the server. When a computer/browser fails, there is no GET request that is received by the Django web server and the browser display a:

This webpage is not available

ERR_CONNECTION_TIMED_OUT
(and sometimes it may be other error messages on other people's computer)

This seems to be the main issue but I'm at a crossroads as to how to fix it. I'm not sure if the network connections are at fault or if something is happening with the server.

**Comment by tatarsky** [comment] 2016-01-09 01:28
I am on the road until the 17th. I will not have time to look at this in detail until then. However a very important question for you given the firewall rules on the head nodes:

What port are you binding the web server to?

**Comment by hirokomatsui** [comment] 2016-01-09 01:33
Thanks Paul, please take your time. It's 7070

**Comment by tatarsky** [comment] 2016-01-09 01:39
7070/tcp is not allowed from off campus. 

We currently only allow the following and my suggestion if you confirm you want 7070/tcp from "any" is we document and add it.

The allowed ports from "any" are limited to the following:

```
22/tcp  (ssh)
7700-7799/tcp  (ipython range)
80/tcp (generic apache running for some services like ganglia)
6000-6100/udp  (used by mosh ssh wrapp)
```

All ports all allowed to on campus networks that match these subnets. They may be more. UCSD has several ranges. 

```
132.249.0.0/16
137.110.0.0/16
```

I am happy to add 7070/tcp to the list of "allowed from any" but confirm that you are ready for worldwide exposure.

**Comment by tatarsky** [comment] 2016-01-09 02:05
To be clear this doesn't need to wait until the 17th as its basically a one line mod on flhn1. But just please be sure you understand the security implications of it.

**Comment by tatarsky** [comment] 2016-01-09 14:55
As I will be out and about most of today getting items for my son I have added the 7070/tcp allow permitting **any** remote IP to talk to it from the `flhn1` node iptables.

Please be careful ;)  If you wanted a more limited list of subnets we can work on that but you are now able to test your service.

**Comment by hirokomatsui** [comment] 2016-01-09 22:25
Thanks!

**Comment by joreynajr** [comment] 2016-01-10 01:08
Thanks for you help Paul!

**Comment by tatarsky** [comment] 2016-01-10 03:14
No prob folks!

**Comment by joreynajr** [comment] 2016-01-11 18:21
So I was checking up with people to see if they can access the site now and it seems it works for everyone now but I was talking with Angelo, Terry, David and others about the website availability from outside of the UCSD Network and I don't think we want to keep it this way.

Before the 7070/tcp change the issue was that some people could connect will others could not and it seemed to not matter if you were on wireless or ethernet. Can we try adding more subnets?

**Comment by tatarsky** [comment] 2016-01-11 21:24
Sure. We just need to try to determine what those subnets are. So the easiest since I suspect you have web logs is just point me to those files and I'll compare with some other iptables lists I have for another group. I will be in/out again for a few days but I'll try to take a look.

**Comment by tatarsky** [comment] 2016-01-18 17:13
Back and around if you have some web logs that show "legit use" I can try to narrow down the iptables allow. Just point me at the file if you can....

**Comment by joreynajr** [comment] 2016-01-18 18:29
Hi Paul,

Do you think it would be enough to send you the output of the Django webserver? Or would the weblogs be coming from somewhere else?

**Comment by tatarsky** [comment] 2016-01-18 18:30
Sure. Basically all I'm looking for is some collection of IP addresses from the ranges that were blocked before so I can add them. I have a list of "UCSD subnets" I can compare to. Alternately I can just add that same list and see who still gets blocked.

**Comment by joreynajr** [comment] 2016-01-18 18:39
Can we try the second option. Now that the website is available from everywhere it's hard to pinpoint who it did work for and who it didn't. Also, I am a little unsure of the Django server output because what I noticed (and I think that Hiroko noticed this as well) is that for people whose computer doesn't connect to the website, the Django server doesn't even seem to get the request and so logging Django server output wouldn't provide anything except for those computers whose request was successful.   

About the collection of IP addresses, could I collect these by going to people's computers and looking at their network settings?

**Comment by joreynajr** [comment] 2016-01-18 18:39
Also I want to develop the webpage a little bit today. So could be try this out tomorrow morning?

**Comment by tatarsky** [comment] 2016-01-18 18:41
Yeah totally on tomorrow. 

The below is probably easiest. I'll revert the firewall back to before when you are ready and then people blocked can simply do the following:

Anybody who finds themselves blocked can request this fake URL below as 80/tcp is "permit any" and I can scrape the log for it. 

http://flh1.ucsd.edu/djangoip.html

**Comment by tatarsky** [comment] 2016-01-18 18:44
For example somebody just clicked from 132.239.163.76. Which is a subnet not in the original list. 
I have added it for when we cut off "any"

**Comment by tatarsky** [comment] 2016-01-18 18:44
(That subnet being confirmed to belong to UCSD...)

**Comment by joreynajr** [comment] 2016-01-18 18:50
132.239.163.76 was probably me and I also had troubles using the current computer before the switch to "permit any". Since almost everyone is here by 10:30 we can try all this then.

**Comment by tatarsky** [comment] 2016-01-18 18:51
That subnet BTW appears to cover the dynamic DHCP ranges for your lab. I'm comparing with various ssh login ips as well to try to "pre-guess" where people are. 

Bottom line: tell me when you want to try again cutting off "any" but hopefully that alone will help.

**Comment by joreynajr** [comment] 2016-01-18 19:36
Sounds good! Let's do 10:30 SD time. I'll send an email (after we change from "any") to everyone so that they try accessing the Cardips website as well as the fake URL you made to capture the log information.

**Comment by tatarsky** [comment] 2016-01-18 19:37
Sounds like a plan.

**Comment by joreynajr** [comment] 2016-01-19 18:08
Hi Paul,

This is the email that I want to send over to everyone so they try out both the Cardips website and the fake URL you mentioned. Let me know if you think it needs any modifications or anything.

“””
Hi All, 

I would like to ask you a favor. At 10:45 Paul will change the Cardips website permissions. Could everyone please try to access the following links at 10:50. Don’t worry about whether you can reach the Cardips website. We will use the results to troubleshoot connection problems. 

Cardips URL: http://flh1.ucsd.edu/djangoip.html/
Testing ULR: http://flh1.ucsd.edu/djangoip.html
"""

**Comment by tatarsky** [comment] 2016-01-19 18:19
Are you sure about the first URL? 

I'd like them to only hit that testing URL if they _CANNOT_ reach your Django site.

**Comment by tatarsky** [comment] 2016-01-19 18:21
So I would say:

Please try to access the Django site at (something something port 7070) and if you find you can no longer reach it please go to the following link. Please note we are only allowing UCSD networks to connect. We are not attempting to support arbitrary outside addresses.

http://flh1.ucsd.edu/djangoip.html

**Comment by joreynajr** [comment] 2016-01-19 18:31
I was talking with Hiroko about proceeding with this. I was worried about making the site available due to possible HIPPA type information but after discussing some, it actually doesn't look like that will be an issue. So we can keep the site with the "any" permission. Sorry for the misunderstand but thanks for the help.

**Comment by tatarsky** [comment] 2016-01-19 18:34
Cool. Not a problem. Basically the application looked like it had authentication. So thats fairly reasonable for most such things. Closing but if you change your mind or others have similar needs this is a way we can easily determine firewall holes.

**Closed as completed by tatarsky** 2016-01-19 18:34 UTC
