### ISSUE TITLE
Install of SpeedSeq

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#15] opened 2015-11-02 21:54 UTC
Interested in installing and trying SpeedSeq tool- however this is a complicated install that requires installing several things that need root access- I'm not sure the best way to proceed with such a software.  Hiroko mentioned that it may be best to have a tool like this in its own environment. 

Refer to this github file for an install example to see what I mean.  

https://github.com/hall-lab/speedseq/blob/master/example/example_speedseq_install.sh

**Comment by tatarsky** [comment] 2015-11-02 22:06
I assume by "its in own environment" you mean perhaps a separate tree with its needed dependencies contained within it. I will scan the above link and make a recommendation. Then its up to you folks if you want my time spent building it or somebody elses. Happy however to "co-battle" .

**Comment by tatarsky** [comment] 2015-11-02 22:10
Doesn't look too bad. I am happy to give it a try and make a "module" out of it per some of the conversations going around. Just confirm that it is ok with Hiroko.

**Comment by tatarsky** [comment] 2015-11-02 22:19
First batch of pre-reqs loaded. While that install script is based on Amazon's Linux its pretty close. Building CNVnator just to see if those pre-reqs were correct....

**Comment by hirokomatsui** [comment] 2015-11-02 22:20
It's totally ok for me. I was thinking to install base modules on the system, and others on the user local environment. But we might not able to separate them very clearly such as the tools we commonly use but not in the Linux base.

**Comment by tatarsky** [comment] 2015-11-02 22:22
Yeah, I'm mapping the items that start with "yum" or "pip" to a common repo that is very equivalent. I'll save my steps but agree with you completely. Yet me run down this build list and see what a good blend of "add to system" and "add to user list" is.

**Comment by tatarsky** [comment] 2015-11-02 22:50
Noting for reference. Added the below to hn1/hn2. 

```
yum install  python27 python27-devel python27-pip lapack lapack-devel blas blas-devel pysam27_083 numpy27 scipy27 libX11-devel libXpm-devel libXft-devel libXext-devel
```

With runtimes to go on nodes once confirmed.

**Comment by tatarsky** [comment] 2015-11-02 23:15
As I head past line 33 of the example script be aware the CERN root software has a module:

```
module add root
```

**Comment by tatarsky** [comment] 2015-11-02 23:19
Perl modules in line 54 added all headnodes/nodes. Speedseq building. Have to make dinner. Back shortly.

**Comment by tatarsky** [comment] 2015-11-03 00:27
Will battle again in the morning. Some complexities in a few of the dependencies I need to have less "day after travel" mind to tackle. I believe I have all the items that are good matches for RPM (yum) loading. 

Note carefully:

default `python` in Centos is older 2.6. This cannot change or numerous admin tools break.

`python27` is the RPM loaded python. My recommendation remains for most folks using an Anaconda personal python tree.

**Comment by djakubosky** [comment] 2015-11-03 00:29
Sounds good, I've set up such an anaconda python tree already so we should be okay, thanks for the help!

**Comment by tatarsky** [comment] 2015-11-03 14:33
Please refer to line 61 of that install script and confirm thats indeed the annotations you want to build as a central cache (if I'm understanding that part right).

Everything above that line is built and installed as modules. Before I do the next sections I want to confirm that the right human reference GRCh37 is being used for your efforts.

To properly use this code so far add the following to your bash startup files:

```
module add root speedseq
```

**Comment by djakubosky** [comment] 2015-11-03 18:45
Yes, those annotations will be okay for what we are doing and so will GRCh37

**Comment by tatarsky** [comment] 2015-11-03 19:01
OK. I will continue from those steps and advise shortly.

**Comment by tatarsky** [comment] 2015-11-03 19:43
Noting for reference vep_cache is located at:

```
/frazer01/software/speedseq-20151103/annotations/vep_cache
```

Downloads in progress. (This is Line 61)

**Comment by tatarsky** [comment] 2015-11-03 20:21
Chewing along. Line 81 now. Not sure of the test methods you will use but am approaching I believe the end.

**Comment by djakubosky** [comment] 2015-11-03 20:50
Great, when this finishes I have a test ready to try this tool, will confirm whether things are working

**Comment by tatarsky** [comment] 2015-11-03 21:51
Look at line 91 and the python items there. My suggestion is you consider those as part of your Anaconda.

Everything up to that point I believe is now done.

You will want to add to your bash startup:

`module add root speedseq`

Assuming it knows where everything ended up is the key part.

**Comment by tatarsky** [comment] 2015-11-03 21:53
Oh and the items in lines 75-86 are located in:

```
/frazer01/software/speedseq-20151103/annotations/cnvnator_chroms
```

I don't know if you have to tell it that or not.

**Comment by djakubosky** [comment] 2015-11-04 01:44
As for gemini, this tool is not a simple anaconda package, and after trying to get this install to work myself and failing I think it would be better if we installed it in our group software directory- and gave it a module,  Other members of the group will want to use this outside of the speedseq software.  

Not totally sure of the best way to do this, as it contains its own anaconda distribution.  

I opened a new issue for this install

Thanks!

**Comment by tatarsky** [comment] 2015-11-04 01:47
Noted. I'll build it via system python27 shortly.

**Comment by tatarsky** [comment] 2015-11-04 15:42
See #20 but basically "please test"

**Comment by tatarsky** [comment] 2015-11-04 19:12
Remind to @tatarsky to check into Git repos once confirmed.

**Comment by tatarsky** [comment] 2015-11-04 21:18
I may rebuild the speedseq items. I don't like the way they came out in terms of its config. Its one of those "directory in place" items.

You may want to try this line yourself with your versions of python. This one may not be a good candidate for sharing as it seems to embed paths and other items from the building environment a bit. 

```
# Get SpeedSeq (tested on commit cb097f33f37710c6be1ffe9256ee39983a776769)
mkdir code
cd code
git clone --recursive https://github.com/cc2qe/speedseq.git
cd speedseq
make
```

**Comment by tatarsky** [comment] 2015-11-04 21:21
Yeah, it stuffs a hardwired python: 

```
        @echo "PYTHON=`which python2.7`" >> $(TARGET_BIN)/speedseq.config
```

**Comment by tatarsky** [comment] 2015-11-04 21:22
So the question is really this:

Do we maintain a central anaconda or system python27 or perhaps do we simply see if we can have speedseq just run with the users python in the path.

**Comment by tatarsky** [comment] 2015-11-04 21:24
Short term idea for test I can wire it to use your personal anaconda I believe. Just to verify that is the issue.

```
speedseq.config

PYTHON=/usr/bin/python2.7

```

I could alter that to:

```
/frazer01/home/djakubosky/software/anaconda/bin/python
```

Advise.

**Comment by djakubosky** [comment] 2015-11-04 21:25
For reference I'm using SpeedSeq in this manner

speedseq sv -B /frazer01/projects/CARDIPS/pipeline/WGS/alignment_bwa/001a6b85-bf54-4e81-b4f7-cff27a06e863/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam -R /frazer01/publicdata/GATK_bundle/b37/human_g1k_v37_decoy_Sendai.fasta -t 8 -g -A

We get this error now to try to find the VEP path- but no more pysam error
Error: VEP not found. Please set path in /frazer01/software/speedseq-20151103/bin/speedseq.config file

**Comment by djakubosky** [comment] 2015-11-04 21:26
Yes that would work- The test I just tried I had my python path set to my python /frazer01/home/djakubosky/software/anaconda/bin/python

**Comment by tatarsky** [comment] 2015-11-04 21:30
OK. One sec. I'm fixing this speedseq.config file which is generated in a really poor way.

**Comment by tatarsky** [comment] 2015-11-04 21:34
Try again. Still fixing some lines but think I have bulk...

**Comment by djakubosky** [comment] 2015-11-04 21:35
I still get the pysam error
See below: 

Running LUMPY express
Sourcing executables from /frazer01/software/speedseq-20151103/bin/speedseq.config ...

Checking for required python modules (/usr/bin/python2.7)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pysam

**Comment by tatarsky** [comment] 2015-11-04 21:38
OK. I changed the PYTHON= line to your Anaconda for test purposes.

**Comment by djakubosky** [comment] 2015-11-04 21:41
A new error-  maybe my pysam isn't right either

Running LUMPY express
Sourcing executables from /frazer01/software/speedseq-20151103/bin/speedseq.config ...

Checking for required python modules (/home/djakubosky/software/anaconda/bin/python)...

```
create temporary directory
```

Traceback (most recent call last):
  File "/frazer01/software/speedseq-20151103/bin/bamlibs.py", line 79, in <module>
    sys.exit(main())
  File "/frazer01/software/speedseq-20151103/bin/bamlibs.py", line 74, in main
    get_libs(args.input, args.is_sam, True)
  File "/frazer01/software/speedseq-20151103/bin/bamlibs.py", line 44, in get_libs
    in_bam = pysam.Samfile(bam, 'rb', check_sq=False)
  File "csamtools.pyx", line 463, in csamtools.Samfile.**cinit** (pysam/csamtools.c:4758)
  File "csamtools.pyx", line 476, in csamtools.Samfile._open (pysam/csamtools.c:5052)
TypeError: _open() got an unexpected keyword argument 'check_sq'

**Comment by tatarsky** [comment] 2015-11-04 21:41
OK. Well I'm building a system pysam27 so it will be a moment.

**Comment by tatarsky** [comment] 2015-11-04 21:43
This as noted by @cdeboever3 is a place where dragons dwell....

**Comment by tatarsky** [comment] 2015-11-04 21:43
We will want to understand precisely what components get used by this animal....

**Comment by tatarsky** [comment] 2015-11-04 21:48
OK. So I see what the one RPM repo for python 27 are doing. 

They are actually allowing multiple version of pysam to exist and use yes, a module, for the user to select which one (using PYTHONPATH).

Give me a moment to mull this over.

**Comment by tatarsky** [comment] 2015-11-04 22:07
OK. This will seem overly complex but there will be a method in the madness in the end.

Try the following to fully use the system python _AND_ select a particular version of pysam for this test.

```
module add python/2.7/pysam/0.8.3 
```

Then run your command.

**Comment by djakubosky** [comment] 2015-11-04 22:17
interestingly when I import this module and just try to import pysam from the python shell I get this error still, so I'm not sure if it worked

> > > import pysam
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:1: RuntimeWarning: compiletime version 2.7 of module 'pysam.libchtslib' does not match runtime version 2.6
> > >   from pysam.libchtslib import *
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:3: RuntimeWarning: compiletime version 2.7 of module 'pysam.ctabix' does not match runtime version 2.6
> > >   import pysam.ctabix as ctabix
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:3: RuntimeWarning: compiletime version 2.7 of module 'pysam.TabProxies' does not match runtime version 2.6
> > >   import pysam.ctabix as ctabix
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:5: RuntimeWarning: compiletime version 2.7 of module 'pysam.csamfile' does not match runtime version 2.6
> > >   import pysam.csamfile as csamfile
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:5: RuntimeWarning: compiletime version 2.7 of module 'pysam.calignmentfile' does not match runtime version 2.6
> > >   import pysam.csamfile as csamfile
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:5: RuntimeWarning: compiletime version 2.7 of module 'pysam.cfaidx' does not match runtime version 2.6
> > >   import pysam.csamfile as csamfile
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:11: RuntimeWarning: compiletime version 2.7 of module 'pysam.cvcf' does not match runtime version 2.6
> > >   import pysam.cvcf as cvcf
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:13: RuntimeWarning: compiletime version 2.7 of module 'pysam.cbcf' does not match runtime version 2.6
> > >   import pysam.cbcf as cbcf
> > > /usr/local/pysam27/0.8.3/pysam/**init**.py:15: RuntimeWarning: compiletime version 2.7 of module 'pysam.csamtools' does not match runtime version 2.6
> > >   import pysam.csamtools as csamtools

**Comment by tatarsky** [comment] 2015-11-04 22:19
`python` or `python27` ?
Very important difference. The fact I see "runtime version 2.6" implies to me you are running /usr/bin/python which in CentOS is version 2.6.

**Comment by djakubosky** [comment] 2015-11-04 22:19
But it does appear to be working when I run my command, can you explain how this works?

**Comment by tatarsky** [comment] 2015-11-04 22:19
See above ;)

**Comment by tatarsky** [comment] 2015-11-04 22:19
The speedseq script forces the use of /usr/bin/python27. Now, the real next test is to make this more sanely usable.

**Comment by tatarsky** [comment] 2015-11-04 22:20
Give me a bit to think about that. I'd like see if I can get this to work with a personal anaconda. But I have a feeling its very tied to the environment it gets built under. Due to all the untangling I just looked at.

**Comment by tatarsky** [comment] 2015-11-04 22:23
This BTW is only fully working on the head node at this moment in time. I am deciding how to deal with pysam. @cdeboever3 do you have any opinions on the version of pysam you prefer? The Princeton Computational repo seems to like:

```
pysam27_083 0.8.3
```

**Comment by djakubosky** [comment] 2015-11-04 22:23
After talking with @cdeboever3, we think its more important to make gemini sanely usable than speedseq, as we don't expect to have to use this pipeline tool more than once or twice to call our variants.

**Comment by cdeboever3** [comment] 2015-11-04 22:28
I'm fine with whatever pysam version you want to go with for python27. It
will only be an issue if we install something later on that wants to use
python27 and needs a different version of pysam.

Expanding on David's note, speedseq is a "pipeline" tool that will most be
automated, so it doesn't matter how ugly the environment is as long as we
can load a module or something and run it. Once we run process data with
speedseq, we shouldn't need to use speedseq until we get new data. Gemini,
however, is an analysis tool that will be used heavily throughout analyses
and probably in a variety of ways (from jupyter notebooks, R, command line,
etc.) from a variety of environments. We'll want some flexibility there.

**Comment by tatarsky** [comment] 2015-11-04 22:28
OK. Well, how does one test gemini? Its currently built as its own package per the instructions and a simple module points to it:

```
module add gemini
```

Which basically brings in "its world" which is a self contained mini-conda python it carries around in the directories under `/frazer01/software/gemini-20151103`

**Comment by tatarsky** [comment] 2015-11-04 22:37
I think for now then on pysam I will set the needed PYTHONPATH to use the system version for the `python27` binary to automatically use that version. So it does not come up "not found". I will do this shortly on all nodes and head nodes unless I hear otherwise. 

This I don't think impacts gemini (as it uses its own python tree) but let me know if you have issues.

**Comment by cdeboever3** [comment] 2015-11-04 22:39
Thanks. I don't have a test case for Gemini (other than however speedseq
uses it, which David will be testing shortly). I just didn't want you to
strain over speedseq too much. I'll update if Gemini isn't working as we
need.

**Comment by tatarsky** [comment] 2015-11-04 22:42
Ha! Appreciated. Now that I can wire its needs up I have some ideas to proceed. Just to confirm one item. That command you gave me as a speedseq test does that overwrite any of the paths it lists? Aka is it safe for me to run (as me)?

**Comment by djakubosky** [comment] 2015-11-04 22:46
I think it should be safe for you to run as well, I have this running now-

speedseq sv -B /frazer01/projects/CARDIPS/pipeline/WGS/alignment_bwa/001a6b85-bf54-4e81-b4f7-cff27a06e863/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam -R /frazer01/publicdata/GATK_bundle/b37/human_g1k_v37_decoy_Sendai.fasta -t 8 -d -g -A 

speedseq sv produces a bgzipped, indexed VCF file. Like this:
outprefix.sv.vcf.gz

**Comment by tatarsky** [comment] 2015-11-04 22:52
OK. I'll use the above again as a test on a node in a bit. As speedseq is just a bash shell, I'm going to likely place the PYTHONPATH in the speedseq.config file that it sources and comment why.

**Comment by tatarsky** [comment] 2015-11-04 23:01
OK. I believe this tool will now run on the nodes as well. And the second head node.

**Comment by djakubosky** [comment] 2015-11-04 23:06
Hopefully, I'm anxious to see what happens when the tool calls CNVnator (which needs root module)- we had a lot of trouble getting this tool to work on the old cluster, and then eventually Gemini

**Comment by tatarsky** [comment] 2015-11-04 23:08
Just keep that stdout/stderr coming and I'm sure we can dig it out. But yeah, its a baroque collection.

**Comment by tatarsky** [comment] 2015-11-04 23:15
BTW, I believe this is the final collection of modules you will need:

```
module add root speedseq gemini
```

You can I believe drop the python item I sent. 

I would add that to a startup shell file.

**Comment by djakubosky** [comment] 2015-11-05 00:01
Will I need to remove my anaconda from my path in order to run?

**Comment by tatarsky** [comment] 2015-11-05 00:09
I do not believe so. But please advise if you see otherwise. I believe it is hardwired to use /usr/bin/python27. But I cannot guarantee it as its quite the web...

**Comment by djakubosky** [comment] 2015-11-05 04:13
Test fails at usage of SVtyper- not entirely sure why-
LUMPY Express done
usage: svtyper [-h] -B BAM -S SPLIT_BAM [-i INPUT_VCF] [-o OUTPUT_VCF]
               [-f SPLFLANK] [-F DISCFLANK] [--split_weight SPLIT_WEIGHT]
               [--disc_weight DISC_WEIGHT] [-n NUM_SAMP] [-M] [--debug]
svtyper: error: argument -S/--split_bam: expected one argument

produces a Lumpy VCF file- all output from this test can be found here 
/frazer01/home/djakubosky/Speed_Seq_Test/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam.SQrBcdUFot5l

Rerunning with a -v flag to capture more verbose stdout and also re-running without the SVtyper flag (-g)
to see if we can get through the rest with out this tool- Note we have had problems with this tool on the other cluster.

**Comment by tatarsky** [comment] 2015-11-05 14:37
Let me know what you see. We can also add "-x" to the parent bash script `speedseq` and have it output all the script items it does.

**Comment by djakubosky** [comment] 2015-11-05 19:33
I got the same issue as before, where svtyper doesn't seem to come through, and another issue when I don't genotype the calls with -g that has something to do with cnvnator- and might be related to our reference genome. but i'm unsure. 

you can find std out/ error here 
with -g parameter set and svtyper error
/frazer01/home/djakubosky/Speed_Seq_Test/error
/frazer01/home/djakubosky/Speed_Seq_Test/stdout

without -g parameter:
/frazer01/home/djakubosky/Speed_Seq_Test/Error_2
/frazer01/home/djakubosky/Speed_Seq_Test/Out_2

**Comment by djakubosky** [comment] 2015-11-06 22:02
We are having an issue with the reference genome used to build CNVnator chroms in line 83 of install script- turns out I advised you to build with one that wouldn't work with what we used for alignments. 

Can I remove and build a new set of annotations here?
/frazer01/software/speedseq-20151103/annotations/cnvnator_chroms

going to use this reference genome instead:
/frazer01/publicdata/GATK_bundle/b37/human_g1k_v37_decoy_Sendai.fasta 

has some extra stuff in it we didn't anticipate effecting our testing

**Comment by djakubosky** [comment] 2015-11-07 00:05
It appears that the module for root doesn't work quite right when used in this fashion
as you can see root doesn't get added to the path

djakubosky@fl-hn1:/frazer01/home/djakubosky/SS_Test_Trunc$ module add root speedseq gemini
djakubosky@fl-hn1:/frazer01/home/djakubosky/SS_Test_Trunc$ root
bash: root: command not found

Can we fix this module?

Adding root to my path manually to see if this has been causing the failures

Edit: I module load just root, it works, but not all three
djakubosky@fl-hn1:/frazer01/home/djakubosky/SS_Test_Trunc$ module add root
djakubosky@fl-hn1:/frazer01/home/djakubosky/SS_Test_Trunc$ root
**\* DISPLAY not set, setting it to :pts/1:S.0

---
-                                         *
-        W E L C O M E  to  R O O T       *
-                                         *
-   Version   5.34/20    12 August 2014   *
-                                         *
-  You are welcome to visit our Web site  *
-          http://root.cern.ch            *
-                                         *
  *******************************************

**Comment by tatarsky** [comment] 2015-11-07 00:48
Hmm. Thats odd. But I see what you mean.

**Comment by tatarsky** [comment] 2015-11-07 00:48
I will have to look at that. I am unsure of what the chained add would do that.

**Comment by djakubosky** [comment] 2015-11-07 00:49
its not a big deal, if I just add them separately it works, just curious- hopefully speedseq will run through now that this is in path

**Comment by tatarsky** [comment] 2015-11-07 00:51
Yeah, its weird though. I chain stuff all the time. I'll figure it out.

**Comment by djakubosky** [comment] 2015-11-09 20:12
Update- With root in path this software comes to an error that @cdeboever3 and I don't understand- was hoping you could take a look at it when you have a moment.  

Command entered:
speedseq sv -B /frazer01/projects/CARDIPS/pipeline/WGS/alignment_bwa/001a6b85-bf54-4e81-b4f7-cff27a06e863/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam -R /frazer01/publicdata/GATK_bundle/b37/human_g1k_v37_decoy_Sendai.fasta -t 8 -d -v -A > sdout 2> error

Location of error/ Stdout
/frazer01/home/djakubosky/SS_Test3/error
/frazer01/home/djakubosky/SS_Test3/stdout

**Comment by tatarsky** [comment] 2015-11-09 20:23
OK, so it looks like variant_effect_predictor.pl  has some perl dependency that it didn't install....or isn't being picked up. I'll look in a bit.

**Comment by tatarsky** [comment] 2015-11-09 20:28
Appears to be the result of those ensembl tools placing their Bio perl tree in the "bin" directory which is a bit odd. But I've done that for a moment to see if that helps their script but recommend we relocate that to a perl lib tree in speedseq and add it to the Perl INC via the module.

**Comment by djakubosky** [comment] 2015-11-09 23:32
Thanks for the update. Should I re-test now?

**Comment by tatarsky** [comment] 2015-11-09 23:38
Yes. But first make sure when you type `variant_effect_predictor.pl` that it returns its help message and not a problem with its perl libraries....

**Comment by tatarsky** [comment] 2015-11-09 23:38
You should get (assuming you've got the speedseq module loaded)

```
variant_effect_predictor.pl 
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

version 76
by Will McLaren (wm2@ebi.ac.uk)

(etc)
```

**Comment by djakubosky** [comment] 2015-11-09 23:45
Returns help message as expected- Will retry now- Thanks!

**Comment by djakubosky** [comment] 2015-11-11 00:37
Okay, I think we are almost there, one last problem- having a similar issue as before in this thread- when the speedseq tries to call svtyper it can't find the pysam module (nor can I import this module when I'm in python27). Can we add this?

**Comment by djakubosky** [comment] 2015-11-11 00:37
/frazer01/home/djakubosky/SS_Test6$ /usr/bin/python27 /frazer01/software/speedseq-20151103/bin/svtyper -i 001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam.yrtq9v80Cgf2/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam.sv.vcf -B /frazer01/projects/CARDIPS/pipeline/WGS/alignment_bwa/001a6b85-bf54-4e81-b4f7-cff27a06e863/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam -S  > 001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam.yrtq9v80Cgf2/001a6b85-bf54-4e81-b4f7-cff27a06e863.mdup.bam.sv.gt.vcf
Traceback (most recent call last):
  File "/frazer01/software/speedseq-20151103/bin/svtyper", line 3, in <module>  
    import pysam  
ImportError: No module named pysam

**Comment by tatarsky** [comment] 2015-11-11 21:49
OK. This confused me for a second because of the "/usr/bin/python27" at the front I thought we fixed the speedseq.config to include the pysam include area

```
export PYTHONPATH=/usr/local/pysam27/0.8.3
```

But was this called "outside" of speedseq's bash shell? In which case I think we need to just toss in that to the speedseq module as well.

**Comment by tatarsky** [comment] 2015-11-11 21:51
OK, which I've done for a test to make sure any binary in the speedseq tree (not just ones called from speedseq's bash script) are properly getting the needed PYTHONPATH.

```
$ module add speedseq
$ svtyper
usage: svtyper [-h] -B BAM -S SPLIT_BAM [-i INPUT_VCF] [-o OUTPUT_VCF]
               [-f SPLFLANK] [-F DISCFLANK] [--split_weight SPLIT_WEIGHT]
               [--disc_weight DISC_WEIGHT] [-n NUM_SAMP] [-M] [--debug]
svtyper: error: argument -B/--bam is required
$ echo $PYTHONPATH
/usr/local/pysam27/0.8.3
```

Tell me if I made it better or worse ;)

**Comment by djakubosky** [comment] 2015-11-11 21:57
thanks! will try now, it definitely does call it outside the speedseq bash shell

**Comment by djakubosky** [comment] 2015-11-12 22:52
for some reason calling variant_effect_predictor.pl after loading speedseq module now gives an error like this 

Can't locate CGI.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /frazer01/software/speedseq-20151103/bin/variant_effect_predictor.pl line 45.
BEGIN failed--compilation aborted at /frazer01/software/speedseq-20151103/bin/variant_effect_predictor.pl line 45.

any idea why? did something change?

**Comment by djakubosky** [comment] 2015-11-12 22:59
Update, only an issue on head node 2, I know you were making some changes there. 
I can move over to HN1

**Comment by tatarsky** [comment] 2015-11-12 23:00
Oh, weird. I must have missed an item on HN2.

**Comment by tatarsky** [comment] 2015-11-12 23:24
The command used to install the needed perl items contained some items that required quoting properly when I sent it via pdsh to the other systems. Currently I believe hn1 and hn2 are correct and will get the nodes after dealing with another matter.

**Comment by tatarsky** [comment] 2015-11-16 15:24
Please note I believe I have added all the dependencies on the nodes and you should consider trying a run via a qlogin to a node sometime.

**Comment by djakubosky** [comment] 2015-11-16 22:23
Will do soon- troubleshooted some things through the speedseq git- making relevant files needed to do a test now. Thanks!!

**Comment by djakubosky** [comment] 2015-12-11 20:37
Hi Paul, I noticed that root doesn't act the same on the compute nodes as it does on the scheduled nodes.  Something may need to be set system wide, this will screw up speedseq (doing my testing on cluster nodes now).

On head nodes:
djakubosky@fl-hn2:/frazer01/home/djakubosky$ root
**\* DISPLAY not set, setting it to fl-hn1:0.0

---
-                                         *
-        W E L C O M E  to  R O O T       *
-                                         *
-   Version   5.34/20    12 August 2014   *
-                                         *
-  You are welcome to visit our Web site  *
-          http://root.cern.ch            *
-                                         *
  *******************************************

ROOT 5.34/20 (v5-34-20@v5-34-20, Aug 13 2014, 15:08:24 on linuxx8664gcc)

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.
root [0] 

on scheduled nodes:

djakubosky@fl-n-1-10:/frazer01/home/djakubosky$ module load root 
djakubosky@fl-n-1-10:/frazer01/home/djakubosky$ root
root: can't figure out DISPLAY, set it manually
In case you run a remote ssh session, restart your ssh session with:
=========>  ssh -Y

**Comment by tatarsky** [comment] 2015-12-11 20:43
That is telling you when you are running on the nodes that it can't find DISPLAY which is an X11 specific item and doesn't make sense for a scheduled job. 

Its giving you a suggestion with the `ssh -Y` to forward X11 if you really wanted X11 support for an interactive session. 

Does your use of root require X11?

**Comment by djakubosky** [comment] 2015-12-11 20:48
I think it does require this- in past experience when I can't load the root
commandline this CNVntor fails- I can just try it this way and see though

On Friday, December 11, 2015, tatarsky notifications@github.com wrote:

> That is telling you when you are running on the nodes that it can't find
> DISPLAY which is an X11 specific item and doesn't make sense for a
> scheduled job.
> 
> Its giving you a suggestion with the ssh -Y to forward X11 if you really
> wanted X11 support for an interactive session.
> 
> Does your use of root require X11?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/15#issuecomment-164043079.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment] 2015-12-11 20:53
Have you tried exporting a fake $DISPLAY or something? Aka:

`export DISPLAY=:0`

But this isn't something I can define at a system level. Its part of X11. 

qlogin also supports a `-display` arguement to pass one along in case you really need X11 back to your desktop for an interactive session. 

qsub can also pass your environment over to a shell.

**Comment by tatarsky** [comment] 2015-12-11 20:54
So here I make a fake $DISPLAY and I assume nothing will really require X11:

```
fl-hn1 [~]$ qlogin
fl-n-1-10 [~]$ module add root
fl-n-1-10 [~]$ root
root: can't figure out DISPLAY, set it manually
In case you run a remote ssh session, restart your ssh session with:
=========>  ssh -Y
fl-n-1-10 [~]$ 

fl-n-1-10 [~]$ export DISPLAY=:0
fl-n-1-10 [~]$ root
  *******************************************
  *                                         *
  *        W E L C O M E  to  R O O T       *
  *                                         *

```

Does that work?

**Comment by djakubosky** [comment] 2015-12-11 22:16
Thanks for the explanation, I think this will work- I'll run a test tonight

On Fri, Dec 11, 2015 at 12:54 PM, tatarsky notifications@github.com wrote:

> So here I make a fake $DISPLAY and I assume nothing will really require
> X11:
> 
> fl-hn1 [~]$ qlogin
> fl-n-1-10 [~]$ module add root
> fl-n-1-10 [~]$ root
> root: can't figure out DISPLAY, set it manually
> In case you run a remote ssh session, restart your ssh session with:
> =========>  ssh -Y
> fl-n-1-10 [~]$
> 
> fl-n-1-10 [~]$ export DISPLAY=:0
> fl-n-1-10 [~]$ root
> 
> ---
> -                                         *
> -        W E L C O M E  to  R O O T       *
> -                                         *
> 
> Does that work?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/15#issuecomment-164045252.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment] 2015-12-11 22:48
Let me know if it does not. I have a few other tricks for turning X11 DISPLAY requiring tools into qsub capable items.

**Comment by djakubosky** [comment] 2015-12-14 19:31
132 Error in TGClient::TGClient: can't open display ":0", switching to batch mode...
133  In case you run from a remote ssh session, reconnect with ssh -Y

I get this type of error in my testing- it doesn't ruin everything- I still get output but I am curious as to how to solve it- we don't get this running on head node

**Comment by tatarsky** [comment] 2015-12-14 21:43
Before I go into details on why this is different how familiar are you with the way X11 client and servers work?

**Comment by djakubosky** [comment] 2015-12-14 22:49
I'm not very familiar beyond some google searches haha- feel free to simplify and explain

**Comment by tatarsky** [comment] 2015-12-14 22:53
I will write up a longer version. Just didn't want to be repetitive. It will more likely be tomorrow. Monday entropy cleanup was a bit heavy.

**Comment by djakubosky** [comment] 2015-12-14 22:56
Thanks, much appreciated

**Comment by tatarsky** [comment] 2015-12-15 18:55
OK. So when you are dealing with the environment variable $DISPLAY you have to remember the following about X11 and ssh interaction with it.

A DISPLAY is equivalent to a running X11 server on a monitor somewhere. Usually the one you are sitting at. When you ssh to a remote system, by default usually it performs SSH forwarding.

Try for example the following from your laptop or desktop assuming its running X11 using the `-Y` flag which forwards X11 with a special trusted mode needed to reduce the security complexities of doing such a thing.  (Thats why the code you have keeps asking for `-Y`' compared to the `-X` option)

```
yourdesktop> ssh -Y flh1.ucsd.edu 
fl-hn1> echo $DISPLAY
localhost:10.0   <---- this is a tunneled X11 DISPLAY from ssh to your desktop
fl-hn1> xterm
```

You should get an xterm session that is actually running on the head node but is DISPLAY'ing back to your system X11 server. Any X11 program will honor $DISPLAY and send all those network bits over to your system. 

Now, when you qsub or qlogin a job, that concept of DISPLAY is not trivial to define and really I would argue you do not really want. As you are asking for an X11 connection to be made to your desktop from some group of jobs you just assigned to be run on arbitrary nodes. You are basically asking to "forward the forward of the X11 packets". 

So, most schedulers do not pass DISPLAY to their running jobs as deciding what to set it to requires X11 tunnels or other means to get the X11 connection back to your actual DISPLAY. qsub does not use SSH to run user jobs. 

In the example above I told you to "fake" DISPLAY to :0 which is a shorthand for X11 running on the local system (do an `echo $DISPLAY` on your desktop sometime). Since there is not an X11 server running on a node the code just said "there isn't a display so I'm not going to run graphically"

Which should be fine. Alternately if you can tell the program in question to NEVER run graphically you can probably skip the above game.

If you actually _want_ X11 sessions coming back from nodes to your desktop I need to elaborate more and to be clear its almost never what you really want. It creates mass chaos. 

I hope this makes some sense. If not tell me and I can try to elaborate.

**Comment by djakubosky** [comment] 2015-12-15 19:08
Thank you for the explanation, this makes sense to me (although when I do what you suggested it fails to set a $DISPLAY and tunnel it- my machine is a 2015 MacBook Pro.)  I think we should be okay proceeding in the way you suggested which will be great.

**Comment by tatarsky** [comment] 2015-12-15 19:10
Forgive my Mac ignorance but does the Mac run X11 these days? ssh will not forward a DISPLAY if there isn't one on the system you come from. What does `echo $DISPLAY` say on a terminal app?

**Comment by djakubosky** [comment] 2015-12-15 19:42
It actually says nothing when I do this on my local machine- it isn't set to anything, maybe it doesn't have X11

**Comment by tatarsky** [comment] 2015-12-15 19:53
Sounds like it. Sorry, I don't know Macs much anymore. That will further complicate matters however in that you have no X11 DISPLAY to even forward ;)

The good news is the software seems to detect a lack of X11 and move on.

**Comment by tatarsky** [comment] 2015-12-15 20:05
Generically google searches seem to imply Apple removed X11 support recently. 

https://support.apple.com/en-us/HT201341

I have no idea how true that is or if you really care in this case.

**Comment by cdeboever3** [comment] 2015-12-15 20:20
I've always used [xquartz](http://www.xquartz.org/) for X11 on mac. I don't
have to use X11 much anymore but it's still useful to have around from time
to time.

**Comment by tatarsky** [comment] 2016-01-05 15:10
I believe this item is complete. I'd like to clean up the list a bit so if there is nothing more on this issue, lets close it.

**Comment by djakubosky** [comment] 2016-01-05 15:10
Sounds good

On Tuesday, January 5, 2016, tatarsky notifications@github.com wrote:

> I believe this item is complete. I'd like to clean up the list a bit so if
> there is nothing more on this issue, lets close it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/15#issuecomment-169028937.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment] 2016-01-05 15:17
We can always re-open if we find an issue. Just trying to find the forest through the trees ;)

**Closed as completed by tatarsky** 2016-01-05 15:17 UTC
