### ISSUE TITLE
touch: cannot touch `new.txt': Read-only file system

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#106] opened 2016-02-13 16:55 UTC
This is happening when I try to write to the lustre (although not scratch). Happens on both flh1 and flh2.

```
[~]fl-hn2 $ touch new.txt
touch: cannot touch `new.txt': Read-only file system
```

**Comment by tatarsky** [comment] 2016-02-13 18:13
Will be home shortly and will look.

Paul Tatarsky
paul@clusterguys.com

**Comment by tatarsky** [comment] 2016-02-13 19:06
I am looking at the problem but am unclear on the root cause. No ETA. Advise logout.

**Comment by cdeboever3** [comment] 2016-02-13 19:18
I'm logged out although I noticed that the problem isn't happening anymore. I'll wait to do anything until you give the all clear.

**Comment by tatarsky** [comment] 2016-02-13 19:21
The closest thing I have to an explanation at the moment is this and I am still looking at the matter but logging my knowledge based on the alerts and logs so far. Yes, Lustre is operational at the moment but I continue to check on a few items. In particular the cnX nodes are not amused.

There was an array warning this morning that the SAS path to the metadata volume was not on the preferred path. This means of the two controllers, the array felt that access to one of the LUNS was not coming from the one it prefers. (It tries to balance I/O from the two metadata servers) 

This is not normally a problem but appears to have been a sign of something went wrong on MDS1 in terms of its involvement in being the primary metadata server. I do not know what that problem was.

For whatever reason the failover of metadata between MDS1 and MDS2 appeared to not work or was "stuck" part way is the best way I can describe it. 

Lustre marks the filesystem read only during this situation.

I manually re-issued the failover and after the recovery period I show the filesystem writable again.

I then also rebooted MDS1 and am looking to decide if I want to fail back or perform diagnostics.

For my notes, MDS1 was up for 108 days.

**Comment by cdeboever3** [comment] 2016-02-13 19:25
Thanks Paul. Do you think this may have happened due to some unusual load/usage? I'm going to continue using the cluster for now. I assume everyone that has jobs running may want to check to make sure they weren't affected: @djakubosky , @patfiaux , @hurleyLi @hirokomatsui . I'm guessing if the jobs were writing to the lustre, they were affected.

**Comment by tatarsky** [comment] 2016-02-13 19:26
Its not clear as to the cause. I don't show in the historical graphs any excessive usage. 

Yes, I suspect any job running during this had issues. 

I have opened a ticket with AHPC to see if Intel can give me more information.

**Comment by tatarsky** [comment] 2016-02-13 19:29
Report any nodes remaining that seem to have issues. I am performing some checks.

**Comment by tatarsky** [comment] 2016-02-13 19:31
Obviously if anybody was indeed doing something "different" I'd love to know but at the moment the closest theory I have is that the primary metadata server got upset at a low level and did not properly participate in failover. Remedy of that requires some determination of what exactly happened to it.

**Comment by tatarsky** [comment] 2016-02-13 19:37
I can confirm that the above theory is looking pretty accurate based on the server logs. Whatever happened between MDS1 and the metadata array it did not go well. The matter may be a hardware issue. 

I will not be failing back until I get some additional data from Intel and AHPC.

**Comment by tatarsky** [comment] 2016-02-13 19:49
And to be clear, I believe it within reason to continue to use the cluster while I wait for that information. 
If I feel otherwise I will announce it.

**Comment by hurleyLi** [comment] 2016-02-14 06:04
Hi Paul @tatarsky , do you have any idea what is the exact time of this period? Because I noticed errors also occurred in some of my jobs this morning

```
  cannot open file 'iPSC.OB.KR.chr2.5000.dump.sorted.mat': Read-only file system
Execution halted
```

But unfortunately I can't retrieve the exact time when this error occurred. 
The last fail logs is written at 6:32 and 6:38 (PST) this morning. 

But it looks like the system return to normal after that, because my other jobs are running OK. It looks like they didn't try to read any file in that period. 

I recommend other people check their jobs as well.

**Comment by tatarsky** [comment] 2016-02-14 13:17
That is consistent with when the SAS error happened  when the filesystem went read only. 

The logs on the MDS1 unit appear to declare the start of the SAS trouble to be 5:44AM on 2/13. 

I believe the MDS1 unit went read only for the metadata a few moments after that as a protection and the failover process is where I am still looking as I don't believe it properly fired. 

I believe jobs that didn't write to Lustre would have continued. 

I believe I fixed the matter at approx 11:00AM or so after MDS1 was rebooted and a failover forced to MDS2. (I was out all of Saturday morning at an event)

I am looking at some additional checks but the main item is to determine why that SAS path failed.

**Comment by tatarsky** [comment] 2016-02-17 15:25
Closing this and will track state of Intel/AHPC ticket in #107

**Closed as completed by tatarsky** 2016-02-17 15:25 UTC
